<style>
    #log-container {
        position: fixed;
        top: 25%;
        left: 25%;
        margin-top: -50px;
        margin-left: -50px;
        width: 50%;
        height: 50%;
        background-color: white;
        padding: 20px;
        border: 1px solid #656565;
        box-shadow: #656565 1px 1px 5px;
        border-radius: 3px;
        overflow: scroll;
    }

    .log-extra {
        margin-left: 50px;
    }

    .log-message {
        font-weight: bold;
        font-size: 1.1em;
    }

    .magium-clickbocker {
        width: 100%;
        height: 100%;
        position: fixed;
        top: 0;
        left: 0;
        background-color: rgba(0, 0, 0, 0.2);
        z-index: 10000;
    }
</style>
<div id="log-container-clickblocker" class="magium-clickbocker" style="display: none; ">
    <div id="log-container"></div>
</div>

    <script type="text/javascript">
    function viewLog(element) {
        $('log-container').update();
        $('log-container-clickblocker').show();

        var logJson = element.getAttribute('data-log');
        elements = JSON.parse(logJson);
        $(elements).each(function (value) {
            var container = new Element('div', {'class': 'log-message'});
            container.insert(value.message);
            $('log-container').insert(container);
            if (!value.extra || value.extra.length == 0) return;
            $H(value.extra).each(function (pair) {
                var extra = new Element('div', {'class': 'log-extra'});
                var str = pair.key + ": " + pair.value;
                extra.insert(str);
                $('log-container').insert(extra);
            });
        });

    }

    function closeForm(e) {
        if (e && e.keyCode && Event.KEY_ESC != e.keyCode) return;
        $('log-container-clickblocker').hide();
    }

    document.observe('keydown', closeForm);
    $('log-container-clickblocker').observe('click', closeForm);
</script>
